import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navibar from "@/components/Navibar";
import QueryClientProvider from "@/components/QueryClientProvider";
import {
  HomeIcon,
  CalendarIcon,
  PlusIcon,
  ChatBubbleOvalLeftEllipsisIcon,
  UserIcon,
} from "@heroicons/react/24/outline";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryClientProvider>
      <html lang="en">
      <body
          className={`${geistSans.variable} ${geistMono.variable} flex flex-col min-h-screen antialiased`}
        >

          {/* 顶部导航区域 */}
          
          <header className="w-full bg-[#183728] sticky top-0 text-white px-6 py-4 h-20.5 z-50 shrink-0 [@media(max-width:1261px)]:h-[65px]">
            <nav className="flex items-center justify-between w-full h-full">
              
              {/* 左侧 Logo/标题 */}
              <img
                src="/images/Logo - 1.svg" 
                alt="reKro Logo"
                className="h-9 w-auto ml-3.5"
              >
              </img>
              
              {/* 右侧菜单 */}
              <div className="hidden md:flex space-x-8.5 mr-8.5">
                {/* Home */}
                <a href="#" className="flex flex-col items-center hover">
                  <HomeIcon className="w-7 h-7 mb-1 [@media(max-width:1261px)]:w-[20px]" />
                  <span className="text-base [@media(max-width:1261px)]:h-[16px]">Home</span>
                </a>

                {/* Events */}
                <a href="#" className="flex flex-col items-center hover">
                  <CalendarIcon className="w-7 h-7 mb-1 [@media(max-width:1261px)]:w-[20px]" />
                  <span className="text-base">Events</span>
                </a>

                {/* Connections */}
                <a href="#" className="flex flex-col items-center hover">
                  <PlusIcon className="w-7 h-7 mb-1 [@media(max-width:1261px)]:w-[20px]" />
                  <span className="text-base">Connections</span>
                </a>

                {/* Chat（高亮为黄色） */}
                <a href="#" className="flex flex-col items-center">
                  <ChatBubbleOvalLeftEllipsisIcon className="w-7 h-7 mb-1 text-yellow-400 [@media(max-width:1261px)]:w-[20px]" />
                  <span className="text-base text-yellow-400">Chat</span>
                </a>

                {/* User */}
                <a href="#" className="flex flex-col items-center hover">
                  <UserIcon className="w-7 h-7 mb-1 [@media(max-width:1261px)]:w-[20px]" />
                  <span className="text-base">User</span>
                </a>
              </div>

            </nav>
          </header>

          {/* 中间主体：左侧侧边栏 + 右侧主内容 */}
          <div className="flex overflow-hidden bg-neutral-100 h-[calc(100vh-82px)] [@media(max-width:1261px)]:h-[calc(100vh-65px)]"
            >
            {/* 左侧侧边栏，包含你的 Navibar */}
            <aside className="hidden lg:block w-3/7 bg-neutral-100 p-0 " style={{ marginLeft: '100px' }}>
              <Navibar />
            </aside>

            {/* 右侧主内容区，渲染各个 page.tsx 的内容 */}
            <main className="w-4/7 flex-1 flex flex-col">
              {children}
            </main>
          </div>

          {/* 底部区域 */}
          
          <footer className="relative bg-[#183728] text-white px-6 py-27.5 shrink-0 hidden md:block">
            <div className="flex items-center">
              {/* 左侧 Logo */}
              <img
                src="/images/Logo - 1.svg"
                alt="reKro Logo"
                className="h-24 w-auto ml-16"
              />
            </div>
    
            <div className="absolute inset-0 flex items-center justify-center">
              <div className="flex space-x-6">
                {/* Instagram 图标 */}
                <a href="#" aria-label="Instagram" className="hover:opacity-80">
                  <svg
                    className="w-18 h-18"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="1"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    viewBox="0 0 24 24"
                  >
                    <rect x="2" y="2" width="20" height="20" rx="5" />
                    <path d="M16 11.37A4 4 0 1 1 12.63 8" />
                    <line x1="17.5" y1="6.5" x2="17.51" y2="6.5" />
                  </svg>
                </a>

                {/* LinkedIn 图标 */}
                <a href="#" aria-label="LinkedIn" className="hover:opacity-80">
                  <svg
                    className="w-18 h-18"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth={1}
                    viewBox="0 0 24 24"
                  >
                    <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-4 0v7H10v-7a6 6 0 0 1 6-6z" />
                    <rect x="2" y="9" width="4" height="12" />
                    <circle cx="4" cy="4" r="2" />
                  </svg>
                </a>
              </div>
            </div>            
          </footer>

          <footer className="md:hidden fixed bottom-0 left-0 right-0 bg-[#183728] text-white h-56px flex items-center justify-between w-full " >
            <div className="flex md:hidden space-x-8.5 mr-8.5 flex items-center justify-between w-full ">
                {/* Home */}
                <a href="#" className="flex flex-col items-center hover">
                  <HomeIcon className="w-7 h-7 mb-1 [@media(max-width:1260px)]:w-[20px]" />
                  <span className="text-base [@media(max-width:1260px)]:h-[16px]">Home</span>
                </a>

                {/* Events */}
                <a href="#" className="flex flex-col items-center hover">
                  <CalendarIcon className="w-7 h-7 mb-1 [@media(max-width:1260px)]:w-[20px]" />
                  <span className="text-base">Events</span>
                </a>

                {/* Connections */}
                <a href="#" className="flex flex-col items-center hover">
                  <PlusIcon className="w-7 h-7 mb-1 [@media(max-width:1260px)]:w-[20px]" />
                  <span className="text-base">Connections</span>
                </a>

                {/* Chat（高亮为黄色） */}
                <a href="#" className="flex flex-col items-center">
                  <ChatBubbleOvalLeftEllipsisIcon className="w-7 h-7 mb-1 text-yellow-400 [@media(max-width:1260px)]:w-[20px]" />
                  <span className="text-base text-yellow-400">Chat</span>
                </a>

                {/* User */}
                <a href="#" className="flex flex-col items-center hover">
                  <UserIcon className="w-7 h-7 mb-1 [@media(max-width:1260px)]:w-[20px]" />
                  <span className="text-base">User</span>
                </a>
              </div>
          </footer>
        </body>
      </html>
    </QueryClientProvider>
  );
}
