version: '3.9'

services:
  backend:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    container_name: rekro-backend
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./models:/app/models
    environment:
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
    restart: unless-stopped

  admin-frontend:
    build:
      context: ./frontend/roro-admin
      dockerfile: Dockerfile
    container_name: rekro-admin
    ports:
      - "3001:3000"  # Next.js 启动时监听 3000
    restart: unless-stopped
    depends_on:
      - backend

  user-frontend:
    build:
      context: ./frontend/roro
      dockerfile: Dockerfile
    container_name: rekro-user
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  uploads:
  models:
